class AppImage {
  AppImage._();
  static const assets = 'assets';
  static const images = 'assets/images';
  static const raviLakhtariya = '$images/ravilakhtariya.png';
  static const splash = '$assets/splash.png';
  static const pratilipi = '$images/pratilipi.png';
  static const financeCalculator = '$images/financeCalculator.jpeg';
  static const imagetopdfmaker = '$images/imagetopdfmaker.jpeg';
  static const graphicDesign = '$images/graphic_design.jpeg';
  static const fueloIOS = '$images/fueloiOSApp.jpeg';
  static const metroUI = '$images/metroUI.jpeg';
  static const logoDesign = '$images/logodesign.jpeg';
  static const connectivityFrameworkNotFound = '$images/connectivity_framwork_not_found.png';
  static const frameworkNotFound = '$images/fix_framework_not_found.png';
  static const penicals = '$images/penical.jpeg';
  static const writer = '$images/writer.jpg';
  static const design = '$images/design.png';
  static const develop = '$images/develop.png';
  static const email = '$images/email.png';
  static const ios = '$images/ios.png';
  static const laptop = '$images/laptop.png';
  static const mapPin = '$images/mappin.png';
  static const person = '$images/person.png';
  static const personSmall = '$images/person_small.png';
  static const phone = '$images/phone.png';
  static const promote = '$images/promote.png';
  static const quote = '$images/quote.png';
  static const whatsapp = '$images/whatsapp.png';
  static const write = '$images/write.png';
}